AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless Translate Page

Parameters:
  ApplicationName:
    Type: String
    Default: 'ServerlessTranslatePage'
  FrontPageApiStageName:
    Type: String
    Default: 'ProdStage'

Resources:
  FrontPageApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ServerlessTranslatePageApi
      EndpointConfiguration: REGIONAL
      StageName: !Ref FrontPageApiStageName
  FrontPageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessTranslatePageFrontFunction
      CodeUri: bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'Test Front Function'
      Policies:
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          API_PATH: !Join [ '', [ '/', !Ref FrontPageApiStageName, '/api'] ]
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RestApiId: !Ref FrontPageApi
  MainFunction:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
      - arm64
      FunctionName: ServerlessTranslatePageApiFunction
      CodeUri: api/bin/
      Handler: bootstrap
      MemorySize: 256
      Runtime: provided.al2
      Description: 'Test Translate Function'
      Policies:
      - Statement:
        - Sid: TlanslatePolicy
          Effect: Allow
          Action:
          - translate:TranslateText
          Resource: '*'
      Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
      Events:
        FrontPageApi:
          Type: Api
          Properties:
            Path: '/api'
            Method: post
            RestApiId: !Ref FrontPageApi

Outputs:
  APIURI:
    Description: "URI"
    Value: !Join [ '', [ 'https://', !Ref FrontPageApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref FrontPageApiStageName,'/'] ]
